sonar.projectKey=ahsanali20_note-app
sonar.organization=ahsanali20
sonar.projectName=Note App
#sonar.sourceEncoding=UTF-8

# Include both backend and frontend sources
#sonar.sources=backend,frontend/src

# Exclude things you don’t want scanned
#sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

# Coverage report paths
#sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

