name: Build
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest

    env:
      JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
      MONGO_URL: ${{ secrets.MONGO_URL }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST}}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT}}
      JWT_REFRESH_EXPIRE: ${{ secrets.JWT_REFRESH_EXPIRE}}
      JWT_EXPIRE: ${{ secrets.JWT_EXPIRE}}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME}}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY}}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET}}
      PORT: ${{ secrets.PORT}}
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      # --- Backend setup & coverage ---
      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Run backend tests with coverage
        working-directory: backend
        run: npm test -- --coverage || true

      # --- Frontend setup & coverage ---
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Run frontend tests with coverage
        working-directory: frontend
        run: npm run test -- --coverage || true

      # --- SonarQube scan ---
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
